name: Push Image
on:
  workflow_run:
    workflows:
      - Spec App
    branches: master
    types: completed
jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: f1sales-facebook-login
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "image_path=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
      - name: Checkout Stores Infra Manifests
        uses: actions/checkout@v2
        with:
          repository: "f1sales/stores-infra"
          token: ${{ secrets.F1SALES_STORES_INFRA_TOKEN }}
      - uses: imranismail/setup-kustomize@v2
      - run: |
          cd manifests/facebook-login
          kustomize edit set image facebook-login=${{ env.image_path }}
          cd ../../
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "New facebook-login image version! ${{ github.sha }}"
